title: Colorful Musings
author: Melanie Gonzalez
theme: minima
titles_from_headings:
  enabled:     true
description: > # this means to ignore newlines until "baseurl:"
  This website is dedicated to my random musings.

# social links
github_username:  melaniesgonzalez

show_excerpts: true # set to false to remove excerpts on the homepage
